---
- name: Check running Docker containers
  hosts: debian
  become: true
  tasks:

    - name: Gather information about Docker containers
      community.docker.docker_host_info:
        containers: true
        containers_filters:
          status: running
      register: docker_info

    - name: Display running containers
      ansible.builtin.debug:
        msg: "Running container: {{ item.Names[0] }} (Image: {{ item.Image }})"
      loop: "{{ docker_info.containers }}"
      loop_control:
        label: "{{ item.Names[0] }}"
