---
- name: Bestand kopiëren
  hosts: all
  tasks:
    - name: Kopieer lokaal bestand naar remote host
      ansible.builtin.copy:
        src: /home/stefanadmin/ansible/debian_repository_docker.list
        dest: /etc/apt/sources.list.d/ 
        owner: root
        group: root
        mode: '0644'

